# Generated by Django 3.2.5 on 2021-07-03 18:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('theatre_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('screen_number', models.IntegerField(verbose_name='number of screens')),
                ('city', models.CharField(max_length=200)),
                ('state_region', models.CharField(max_length=200, verbose_name='state/region')),
                ('country', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=15)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
