# Generated by Django 3.2.5 on 2021-07-05 16:39

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_auto_20210705_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('screen_number', models.IntegerField(verbose_name='number of screens')),
                ('pincode', models.CharField(max_length=15)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state_region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country')),
                ('state_region', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region', verbose_name='state/region')),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=10)),
                ('screen_format', models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('I2D', 'IMAX 2D'), ('I3D', 'IMAX 3D'), ('4D', '4D'), ('4DX', '4DX'), ('insignia', 'Insignia')], max_length=20)),
                ('seats', models.IntegerField(verbose_name='number of seats')),
                ('theatre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.theatre')),
            ],
        ),
    ]
