# Generated by Django 3.2.5 on 2021-07-03 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_auto_20210703_2052'),
        ('theatre', '0002_alter_theatre_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatre',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country'),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='state_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region', verbose_name='state/region'),
        ),
    ]
