# Generated by Django 3.2.5 on 2021-07-03 21:49

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_auto_20210703_2052'),
        ('theatre', '0003_auto_20210703_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatre',
            name='state_region',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region', verbose_name='state/region'),
        ),
    ]
