# Generated by Django 3.2.5 on 2021-07-03 23:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0009_alter_theatre_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theatre',
            old_name='theatre_id',
            new_name='id',
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('screen_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('screen_format', models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('I2D', 'IMAX 2D'), ('I3D', 'IMAX 3D'), ('4D', '4D'), ('4DX', '4DX'), ('insignia', 'Insignia')], max_length=20)),
                ('seats', models.IntegerField(verbose_name='number of seats')),
                ('theatre_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='theatre.theatre')),
            ],
        ),
    ]
