# Generated by Django 3.2.5 on 2021-07-03 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0010_auto_20210703_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screen',
            old_name='screen_id',
            new_name='id',
        ),
    ]
